name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - run: npm run build

      - name: Version and Publish
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npx changeset version
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: version packages"
            git push
          fi
          npx changeset publish
          npx changeset tag
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
